% this file plots 1 plot. It shows how many adds can be performed 
% for a given set of n and v
close all;
syms n v i_range

Adds = (n^2-n-v*(2*n-1)-1)./(v*(1+n)-n);    %derived function

nValues = [8,16,32,64];  %bitwidths of n

Adds_nSet = simplify(subs(Adds,n,nValues)); %substitute the values of interest
v_vec = (2:10)'; %precicion of graph
legend_str = cellstr(num2str(nValues','n = %d'))';


print

data = subs(Adds_nSet,v,v_vec);
data(data<0) = 0; %when I_TRUE is larger than I_FALSE values get negative

%% plotting for publication
width = 4; %inch
height = 2; %inch

figure('Units','inches',...
'Position',[5 5 width height], ...
'PaperPositionMode','auto');

h = plot(repmat(v_vec,1,length(nValues)),data);
set(h,'Marker','.','MarkerSize',7,'LineWidth',1)
set(gca,...
'Units','normalized',...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',9,...
'FontName','Times')
ylabel({'$N$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',9,...
'FontName','Times')
xlabel('$v$ samples',...
'FontUnits','points',...
'FontWeight','normal',...
'interpreter','latex',...
'FontSize',7,...
'FontName','Times')
legend(legend_str,...
'interpreter','latex',...
'FontSize',7,...
'FontName','Times',...
'Location','NorthEast')
title('Sinusoidal function',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',7,...
'FontName','Times')
matlab2tikz('symbolic_equation_example.tex')


% % %  makes little sense to plot
% % Adds = (n^2-n-v*(2*n-1)-1)./(v*(1+n)-n);    %derived function
% % 
% % Adds = subs(Adds,v,i_range*(n-1)); %replace v by input range
% % 
% % nValues = [16,32,64];  %bitwidths of n
% % 
% % Adds_nSet = simplify(subs(Adds,n,nValues)); %substitute the values of interest
% % i_vec = linspace(0.1,0.5,100)'; %precicion of graph
% % legend_str = cellstr(num2str(nValues','length(n) = %d'))';
% % 
% % 
% % data = subs(Adds_nSet,i_range,i_vec);
% % figure();plot(repmat(i_vec,1,length(nValues)),data)
% % legend(legend_str)

